spring.application.name=student-management

# PostgreSQL config
spring.datasource.url=jdbc:postgresql://dpg-d7mdu9pkh4rs73al34b0-a.oregon-postgres.render.com:5432/student_db_47u1
spring.datasource.username=student_db_47u1_user
spring.datasource.password=IEPV7CNVGwshqxtE19zAaZ8dRG1indhh

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true